table AMZN
	lineageTag: 2a58ba09-542f-490e-913a-dcbdf50daec3

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6651e881-5184-47bc-abf7-b02b0153904a
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: d3d8c4ba-97aa-4266-957d-a06d284e01a7
			defaultHierarchy: LocalDateTable_e6ef803a-ae8e-4a48-b512-a4dedb93797c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Open
		dataType: double
		lineageTag: 609c0809-bb60-481a-afef-720ce923e186
		summarizeBy: sum
		sourceColumn: Open

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column High
		dataType: double
		lineageTag: 859dd130-6c9c-4d17-90a8-2ae576f4a93c
		summarizeBy: sum
		sourceColumn: High

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Low
		dataType: double
		lineageTag: 5ed8e49f-08a7-471d-b5e5-bfbd53c5d667
		summarizeBy: sum
		sourceColumn: Low

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Close
		dataType: double
		lineageTag: 6dd7d5e3-7d6b-421c-b86e-b31e22bcb7b0
		summarizeBy: sum
		sourceColumn: Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Adj Close'
		dataType: double
		lineageTag: 41edba8c-03b5-40f7-968b-218e77117552
		summarizeBy: sum
		sourceColumn: Adj Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Volume
		dataType: int64
		formatString: 0
		lineageTag: c9151ce5-d469-483b-a20a-fc37c889fef6
		summarizeBy: sum
		sourceColumn: Volume

		annotation SummarizationSetBy = Automatic

	partition AMZN = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("F:\Data Learning\1 - PBIP\PBIP\PBIP\AMZN.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Open", type number}, {"High", type number}, {"Low", type number}, {"Close", type number}, {"Adj Close", type number}, {"Volume", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

